openapi: 3.0.0
info:
  version: '1.0'
  title: 'High Body Mass Index in Children and Adolescents: Interventions'
  description: 'Children and adolescents 6 years or older:  
                The USPSTF recommends that Clinicians should provide or refer children and adolescents 6 years or older with a high body mass index (BMI) (≥95th percentile for age and sex) to comprehensive, intensive behavioral interventions.
                Grade: B'
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /endpoints/hight-body-mass-index
    description: Calculate high bmi inclusion
tags:
  - name: KO Endpoints
    description: high bmi inclusion calculation Endpoints    
paths:
  /hbmi:
    post:
      summary: Calculate high bmi inclusion.
      description: Calculates high bmi inclusion.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:  
                age:
                  type: number
                  format: float
                  description: Age of the person
                  example: 35             
                bmi_percentile:
                  type: number
                  format: float
                  description: bmi percentile for age and sex.
                  example: 70.0 
      responses:
        '200':
          description: Successfully calculated high bmi inclusion.
          content:
            application/json:
              schema:
                type: object
                properties:
                  inclusion:
                    type: number
                    format: float
                    description: inclusion
                    example: 0
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
