openapi: 3.0.0
info:
  version: '1.0'
  title: 'Healthy Weight and Weight Gain In Pregnancy: Behavioral Counseling Interventions'
  description: |
                For pregnant adolescents and adults:
                The USPSTF recommends that clinicians offer effective behavioral counseling interventions aimed at promoting healthy weight gain and preventing excess gestational weight gain in pregnancy.
                Grade B
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /endpoints/pregnancy-healthy-weight-gain
    description: Calculate pregnancy healthy weight gain recommendation inclusion
tags:
  - name: KO Endpoints
    description: pregnancy healthy weight gain recommendation inclusion Endpoints    
paths:
  /check-inclusion:
    post:
      summary: Calculate pregnancy healthy weight gain recommendation inclusion.
      description: Calculates pregnancy healthy weight gain recommendation inclusion.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:  
                pregnant:
                  type: boolean
                  description: Indicated if the person is pregnant.
                  example: true             
      responses:
        '200':
          description: Successfully calculated pregnancy healthy weight gain recommendation inclusion.
          content:
            application/json:
              schema:
                type: object
                properties:
                  inclusion:
                    type: number
                    format: float
                    description: inclusion
                    example: 0
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
