openapi: 3.0.0
info:
  version: '1.0'
  title: 'Prediabetes and Type 2 Diabetes: Screening'
  description: |
                Adults aged 35 to 70 years who have overweight or obesity:
                The USPSTF recommends screening for prediabetes and type 2 diabetes. Clinicians should offer or refer patients with prediabetes to effective preventive interventions.
                Grade: B
  contact:
    name: KGrid Team
    email: kgrid-developers@umich.edu
    url: 'http://kgrid.org'
servers:
  - url: /endpoints/diabetes-screening
    description: Calculate diabetes screening inclusion
tags:
  - name: KO Endpoints
    description: diabetes screening inclusion calculation Endpoints    
paths:
  /check-inclusion:
    post:
      summary: Calculate diabetes screening inclusion.
      description: Calculates diabetes screening inclusion.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:  
                age:
                  type: number
                  format: float
                  description: Age of the person
                  example: 35             
                bmi:
                  type: number
                  format: float
                  description: body mass index
                  example: 30.0 
      responses:
        '200':
          description: Successfully calculated diabetes screening inclusion.
          content:
            application/json:
              schema:
                type: object
                properties:
                  inclusion:
                    type: number
                    format: float
                    description: inclusion
                    example: 0
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: 'https://demo.kgrid.org/schemas/openapischemas.yaml#/components/schemas/genericerror'
