[tool.poetry]
name = "prevent-obesity-morbidity-mortality"
version = "1.1"
description = ""
authors = ["Farid Seifi <farid.seifi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.3"
kgrid = {path = "/home/faridsei/dev/code/python-sdk/dist/kgrid-0.2.3-py3-none-any.whl"}

[tool.poetry.scripts]
prevent-obesity-morbidity-mortality = "prevent_obesity_morbidity_mortality.prevent_obesity_morbidity_mortality:cli"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
