[tool.poetry]
name = "cardiovascular-prevention-statin-use"
version = "0.1.0"
description = ""
authors = ["Farid Seifi <farid.seifi@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.3"

[tool.poetry.scripts]
cardiovascular-prevention-statin-use = "cardiovascular_prevention_statin_use.cli_service.cli_service:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
